# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

breg <- function(y, X, betabar, A) {
#' @useDynLib mukera
#' @export
    .Call('mukera_breg', PACKAGE = 'mukera', y, X, betabar, A)
}

rcpparma_hello_world <- function() {
    .Call('mukera_rcpparma_hello_world', PACKAGE = 'mukera')
}

rcpparma_outerproduct <- function(x) {
    .Call('mukera_rcpparma_outerproduct', PACKAGE = 'mukera', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('mukera_rcpparma_innerproduct', PACKAGE = 'mukera', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('mukera_rcpparma_bothproducts', PACKAGE = 'mukera', x)
}

